declare module '@next/eslint-plugin-next'
declare module 'eslint-config-prettier'
declare module 'eslint-plugin-import-helpers'
declare module 'eslint-plugin-jsx-a11y'
declare module 'eslint-plugin-react'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-security'
declare module 'eslint-plugin-unused-imports'
